version: '3'

services:
    react:
        stdin_open: true
        build: bankfront
        ports:
            - "3000:3000"



    node:
        build: bankapi
        ports:
            - "5454:5454"
        links:
            - database

    database:
        image: mongo
        ports:
            - "27017:27017"
    

